# PLAY level variables
#Variable holds a value we can use it anywhere

- name: variables from PLAY level
  hosts: localhost
  vars:
    Course: "DevOps"  #To access variable use curl brackets{{}}
    Trainer: "Sivakumar"
    Duration: "110HRS"
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "Hi, I am learning {{Course}}, Trainer is {{Trainer}}, Duration is {{Duration}}" 