- name: create ec2 and r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-09863c54177764565 # replace with your subnet id
    sg_id: "sg-09a300a3729062c5a"
    ami_id: "ami-09c813fb71547fc4f"
    instances:
    - mysql
    - backend
    - frontend
    zone: daws81s.online
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instances #Resigter will get the information from instances from that output we can create records.

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_instances }}"

  #private IP R53
  - name: create r53 private records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}" #mysql.daws81s.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results }}" #Under the results we have all instances inforamtion.

  - name: create r53 public record for frontend
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ zone }}" #daws81s.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results }}"
    when: item.item == "frontend"


    #Install boto3 and botocore "pip3.9 install boto3 botocore"
    #Assign a role to ansible server or do aws configure
    